name: Generate Snake ğŸ

on:
  schedule:
    - cron: "0 0 * * *"  # Se ejecuta todos los dÃ­as a medianoche
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: MarceloPincheira
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit & Push result
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated contribution grid snake"
          branch: output
          file_pattern: 'dist/*.svg'
